### ISSUE TITLE
Slack message only shows latest resource in manifest

### ISSUE THREAD

**Issue by mtmn** [justinbarrick/fluxcloud#51]
Currently I have created following manifest -
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/permitted: ".*"
  labels:
    name: rbac-testing
  name: rbac-testing
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/permitted: ".*"
  labels:
    name: rbac-testing-ro
  name: rbac-testing-ro
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/permitted: ".*"
  labels:
    name: rbac-testing-misc
  name: rbac-testing-misc
```

the problem is, however, that in the Slack group I can only see the latest resource whereas all the other resources were added as well.

```
Resources updated:
* <cluster>:namespace/rbac-testing-misc
```

This could be either a feature or a bug, not sure.

Thanks!
